name: beambci

dependencies:
  - python=3.12.3
  - pip=24.0
  - numpy=1.26
  - scipy=1.11.3
  - matplotlib=3.8
  - pyqt=5.15
  - pyqt-stubs=5.15
  - pyserial=3.5
  - requests=2.31
  - pydantic=2.5.3
  - colorama=0.4.6
  - websockets=12.0
  - pip:
    - pylsl==1.16.2
    - pyxdf==1.16.4
    - typeguard==4.1.5
    - mne==1.5.1
    - psutil==5.9.6


